--liquibase formatted sql

--changeset root:1598598894891-594
create table contract_bank_accounts
(
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  firstname VARCHAR(255),
  lastname VARCHAR(255)
);
--rollback drop table contract_bank_accounts;

--changeset root:1598598894891-595
create table contract_banks
(
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  firstname VARCHAR(255),
  lastname VARCHAR(255)
);
--rollback drop table contract_banks;

--changeset root:1598598894891-596
drop table contract_bank_accounts;
--rollback create table contract_bank_accounts ( id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, firstname VARCHAR(255), lastname VARCHAR(255));


--changeset root:1598598894891-597
drop table contract_banks;
--rollback create table contract_banks ( id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, firstname VARCHAR(255), lastname VARCHAR(255));
